### ISSUE TITLE
Rename to Net::FTP

### ISSUE THREAD

**Issue by zoffixznet** [araraloren/Net-FTP#11]
Hello,

May I offer a suggestion to rename this module to Net::FTP? Here is my reasoning for the suggestion:

* FTP is an abbreviation for **F**ile **T**ransfer **P**rotocol, so lowercasing part of that abbreviation is unusual
* Other languages spell it as all-caps: Perl 5 and Ruby have  `Net::FTP` and Python has `FTP`

These combined factors would likely result in users of your module accidentally spelling the name as `Net::FTP` instead of `Net::Ftp` and getting errors in the code, installation, or documentation look up. For example, if the search feature on modules.perl6.org was not case-insensitive, your module might not end up being found because most users would type FTP and not Ftp.

My two cents :smile_cat: 

Cheers,
ZZ

**Comment by araraloren** [comment]
Em, I will changed name to Net::FTP

**Comment by zoffixznet** [comment]
Thanks a lot!
