### ISSUE TITLE
Can't get it installed through panda

### ISSUE THREAD

**Issue by 13pass** [araraloren/Net-FTP#17]
```
$ panda install Net::FTP
==> Fetching Net::FTP
fetch stage failed for Net::FTP: Unable to handle source 'https://github.com/araraloren/Net-FTP/'
```

**Comment by araraloren** [comment]
Thanks for your advice.
The original 'source_url' in MEAT.info  is wrong,  I updated it . https://github.com/araraloren/Net-FTP/commit/86148c43d0700d031e5568c35377a547c58cf012
